### PR TITLE
Implemented Landing/Home Page as per the provided figma file

### PR DESCRIPTION
**Pull request by skj1709**
### Changes

1. Implemented the home.jsx as per the figma file.
2. Page is responsive to all devices.

### Note
1. The text under the "feature" section is dummy.
2.  The login page seen in the first GIF is in under process and not a part of this commit.

laptopview

tab mobileView

### CODE REVIEW

**Comment by sikehish** [comment]
Great work @sumit-kumar-jha1709 . 
image
Can you fix the padding in the get started button and the image on the left?

**Comment by skj1709** [comment]
sure @sikehish working on this

**Comment by sumit-kumar-jha1709** [comment]
Hey @sikehish can you please tell me on what screen size this problem of padding is occurring as I've checked it on different screen sizes but it worked absolutely fine.

**Comment by sumit-kumar-jha1709** [comment]
@sikehish I've done some changes in the padding, can you please check it now.

Untitled design

**Comment by skj1709** [comment]
@sikehish can you please check it now, I've updated the necessary padding of "feature" section and the "get started" button and also updated the flex properties for better responsiveness.
Untitled design

**Comment by sikehish** [comment]
It looks fine to me. Good job!

**Pull request merged**
